<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Cuesheets Overview</title>
    <style type="text/css">
      .empty {
        visibility: hidden;
        display: none;
      }
    </style>
  </head>
  <body>
    <form action="" method="get">
      <label for="query">Search:</label>
      <input type="text" id="query" minlength="2" required="required" disabled="disabled" tabindex="1" placeholder="You can search for a title"/>
    </form>
    <div id="resultlist">
    </div>
